
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 25 22:24:05 CST 2019
//----------------------------------------------------

package Parsers;

/** CUP generated class containing symbol constants. */
public class symCapas {
  /* terminals */
  public static final int COMA = 6;
  public static final int EOF = 0;
  public static final int LLAVECERRADA = 4;
  public static final int NUMERO = 7;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int HEXA = 8;
  public static final int LLAVEABIERTA = 3;
  public static final int PUNTOYCOMA = 5;
}

