
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 25 22:28:00 CST 2019
//----------------------------------------------------

package Parsers;

/** CUP generated class containing symbol constants. */
public class symImages {
  /* terminals */
  public static final int COMA = 3;
  public static final int NUMERO = 2;
  public static final int error = 1;
  public static final int LLAVECERRADA = 5;
  public static final int LLAVEABIERTA = 4;
  public static final int EOF = 0;
}

