
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 27 16:43:47 CST 2019
//----------------------------------------------------

package Parsers;

/** CUP generated class containing symbol constants. */
public class symUsers {
  /* terminals */
  public static final int ID = 6;
  public static final int NUMERO = 5;
  public static final int COMA = 4;
  public static final int PUNTOYCOMA = 3;
  public static final int error = 1;
  public static final int DOSPUNTOS = 2;
  public static final int EOF = 0;
}

